apiVersion: v2
name: kubecop-clustered-crds
description: A Helm chart for clustered CRDs required by Kubernetes Runtime Security detection system KubeCop

type: application

version: 0.0.1

appVersion: "0.0.1"
