apiVersion: kubescape.io/v1
kind: ApplicationProfile
metadata:
  name: job-kubecop-malicious-app-job
  annotations:
    kapprofiler.kubescape.io/final: "true"
spec:
  containers:
  - dns:
    - dnsName: dl.k8s.io.default.svc.cluster.local.
    - dnsName: dl.k8s.io.svc.cluster.local.
    - dnsName: dl.k8s.io.cluster.local.
    - dnsName: dl.k8s.io.wework.com.
    - dnsName: dl.k8s.io.
    - dnsName: cdn.dl.k8s.io.default.svc.cluster.local.
    - dnsName: cdn.dl.k8s.io.svc.cluster.local.
    - dnsName: cdn.dl.k8s.io.cluster.local.
    - dnsName: cdn.dl.k8s.io.wework.com.
    - dnsName: cdn.dl.k8s.io.
    execs:
    - args: []
      envs: []
      path: /malicious
    - args:
      - get
      - secrets
      envs: []
      path: ./kubectl
    name: kubecop-malicious-app
    networkActivity:
      outgoing:
      - dstEndpoint: 10.96.0.10
        port: 53
        protocol: UDP
      - dstEndpoint: 34.107.204.206
        port: 443
        protocol: TCP
      - dstEndpoint: 10.96.0.1
        port: 443
        protocol: TCP
      - dstEndpoint: 142.251.37.68
        port: 443
        protocol: TCP
    opens:
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    - flags:
      - O_RDWR
      - O_CREAT
      - O_TRUNC
      - O_CLOEXEC
      path: /kubectl
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/resolv.conf
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/nsswitch.conf
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/hosts
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/ssl/certs/ca-certificates.crt
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/ssl/certs
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /dev/null
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /kubectl
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/http/.diskv-temp/1551865526
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/http/.diskv-temp/1800833511
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/http/.diskv-temp/426388698
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/http/.diskv-temp/1918856183
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/servergroups.json.3433986743
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/monitoring.coreos.com/v1alpha1/serverresources.json.2745914820
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/apiregistration.k8s.io/v1/serverresources.json.1969960625
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/events.k8s.io/v1/serverresources.json.3479875250
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/apps/v1/serverresources.json.2054157207
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/batch/v1/serverresources.json.1122305786
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/node.k8s.io/v1/serverresources.json.3159648480
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/scheduling.k8s.io/v1/serverresources.json.2586561447
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/authorization.k8s.io/v1/serverresources.json.1352712235
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/autoscaling/v1/serverresources.json.3363656822
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/authentication.k8s.io/v1/serverresources.json.2342119690
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/certificates.k8s.io/v1/serverresources.json.829658111
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/autoscaling/v2/serverresources.json.462067726
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/rbac.authorization.k8s.io/v1/serverresources.json.3799750115
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/storage.k8s.io/v1/serverresources.json.1126267597
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/flowcontrol.apiserver.k8s.io/v1beta3/serverresources.json.943762234
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/apiextensions.k8s.io/v1/serverresources.json.3892227372
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/policy/v1/serverresources.json.794447361
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/flowcontrol.apiserver.k8s.io/v1beta2/serverresources.json.4242236479
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/discovery.k8s.io/v1/serverresources.json.462747227
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/v1/serverresources.json.1508407068
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/networking.k8s.io/v1/serverresources.json.3661884975
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/coordination.k8s.io/v1/serverresources.json.1802527156
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/monitoring.coreos.com/v1/serverresources.json.1694752171
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/admissionregistration.k8s.io/v1/serverresources.json.1985586824
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/kubescape.io/v1/serverresources.json.4279283636
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/servergroups.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/apps/v1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/authentication.k8s.io/v1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/autoscaling/v2/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/v1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/monitoring.coreos.com/v1alpha1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/events.k8s.io/v1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/apiextensions.k8s.io/v1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/apiregistration.k8s.io/v1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/networking.k8s.io/v1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/authorization.k8s.io/v1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/batch/v1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/scheduling.k8s.io/v1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/policy/v1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/kubescape.io/v1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/admissionregistration.k8s.io/v1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/node.k8s.io/v1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/flowcontrol.apiserver.k8s.io/v1beta3/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/monitoring.coreos.com/v1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/rbac.authorization.k8s.io/v1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/certificates.k8s.io/v1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/autoscaling/v1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/coordination.k8s.io/v1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/flowcontrol.apiserver.k8s.io/v1beta2/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/storage.k8s.io/v1/serverresources.json
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.kube/cache/discovery/10.96.0.1_443/discovery.k8s.io/v1/serverresources.json
    - flags:
      - O_WRONLY
      - O_CREAT
      - O_CLOEXEC
      path: /malicious.txt
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/sys/net/core/somaxconn
    syscalls:
    - access
    - arch_prctl
    - bind
    - brk
    - capget
    - capset
    - chdir
    - clone
    - close
    - connect
    - dup
    - dup2
    - dup3
    - epoll_create1
    - epoll_ctl
    - epoll_pwait
    - execve
    - exit_group
    - faccessat2
    - fadvise64
    - fchmod
    - fchmodat
    - fcntl
    - fork
    - fstat
    - fstatfs
    - futex
    - getcwd
    - getdents64
    - getegid
    - geteuid
    - getgid
    - getpeername
    - getpgrp
    - getpid
    - getppid
    - getrandom
    - getrlimit
    - getsockname
    - getsockopt
    - gettid
    - getuid
    - ioctl
    - listen
    - lseek
    - lstat
    - madvise
    - mkdir
    - mkdirat
    - mmap
    - mount
    - mprotect
    - munmap
    - nanosleep
    - newfstatat
    - openat
    - pipe
    - pipe2
    - prctl
    - pread64
    - prlimit64
    - read
    - readlink
    - readlinkat
    - renameat
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - sched_getaffinity
    - sched_yield
    - set_robust_list
    - set_tid_address
    - setgid
    - setgroups
    - setns
    - setsockopt
    - setuid
    - sigaltstack
    - socket
    - stat
    - statfs
    - sysinfo
    - tgkill
    - uname
    - unlinkat
    - wait4
    - waitid
    - write
