apiVersion: batch/v1
kind: Job
metadata:
  name: kubecop-malicious-app-job
spec:
  template:
    metadata:
      labels:
        app: kubecop-malicious-app
    spec:
      containers:
      - name: kubecop-malicious-app
        image: quay.io/armosec/kubecop:malicious-app
        env:
          - name: WAIT_FOR_SIGTERM
            value: "true"
          - name: WAIT_BEFORE_START
            value: "120"
      restartPolicy: Never
  backoffLimit: 1
