apiVersion: kubescape.io/v1
kind: ApplicationProfile
metadata:
  labels:
    kapprofiler.kubescape.io/final: "true"
    kapprofiler.kubescape.io/namespace: "default"
  name: deployment-nginx-deployment-default
  namespace: kubescape
spec:
  containers:
  - capabilities:
    - caps:
      - NET_BIND_SERVICE
      syscall: bind
    - caps:
      - CHOWN
      syscall: chown
    - caps:
      - SETGID
      syscall: setgid
    - caps:
      - SETUID
      syscall: setuid
    - caps:
      - SETGID
      syscall: setgroups
    execs:
    - args:
      - -g
      - daemon off;
      path: /usr/sbin/nginx
    name: nginx
    networkActivity: {}
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      - O_NONBLOCK
      path: /usr/share/nginx/html/index.html
    - flags:
      - O_WRONLY
      - O_CREAT
      - O_APPEND
      path: ""
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/group
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/passwd
    - flags:
      - O_RDWR
      - O_CREAT
      - O_TRUNC
      path: /run/nginx.pid
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/ld.so.cache
    - flags:
      - O_RDONLY
      - O_NONBLOCK
      - O_DIRECTORY
      - O_CLOEXEC
      path: /etc/nginx/conf.d
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/nsswitch.conf
    - flags:
      - O_RDONLY
      path: /etc/nginx/mime.types
    - flags:
      - O_RDONLY
      path: /etc/nginx/nginx.conf
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/share/zoneinfo/UTC
    - flags:
      - O_RDONLY
      path: /proc/sys/kernel/ngroups_max
    - flags:
      - O_RDONLY
      path: /etc/nginx/conf.d/default.conf
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /sys/devices/system/cpu/online
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libc-2.24.so
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libdl-2.24.so
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libz.so.1.2.8
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libnsl-2.24.so
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libcrypt-2.24.so
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libpcre.so.3.13.3
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libssl.so.1.1
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libnss_nis-2.24.so
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libpthread-2.24.so
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libnss_files-2.24.so
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libnss_compat-2.24.so
    syscalls:
    - access
    - arch_prctl
    - bind
    - brk
    - capget
    - capset
    - chdir
    - chown
    - clone
    - close
    - connect
    - dup2
    - epoll_create
    - epoll_ctl
    - epoll_pwait
    - epoll_wait
    - eventfd2
    - execve
    - exit
    - faccessat2
    - fchmodat
    - fchownat
    - fcntl
    - fstat
    - fstatfs
    - futex
    - getdents
    - getdents64
    - geteuid
    - getpid
    - getppid
    - getrlimit
    - io_setup
    - ioctl
    - linkat
    - listen
    - lseek
    - madvise
    - mkdir
    - mkdirat
    - mmap
    - mount
    - mprotect
    - munmap
    - nanosleep
    - newfstatat
    - open
    - openat
    - openat2
    - pivot_root
    - prctl
    - pread64
    - pwrite64
    - read
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - rt_sigsuspend
    - sched_yield
    - set_robust_list
    - set_tid_address
    - setgid
    - setgroups
    - setsockopt
    - setuid
    - sigaltstack
    - socket
    - socketpair
    - stat
    - symlinkat
    - sysinfo
    - tgkill
    - umount2
    - uname
    - unlinkat
    - utimensat
    - write
    - dup
    - exit_group
    - fadvise64
    - getcwd
    - getegid
    - getgid
    - getpgrp
    - getuid
    - lstat
    - pipe
    - prlimit64
    - readlink
    - statfs
    - accept4
    - recvfrom
    - sendfile
    - writev
    - wait4
    - event

