apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: runtimerulealertbindings.kubescape.io
spec:
  scope: Cluster
  group: kubescape.io
  versions:
    - name: v1
      served: true
      storage: true      
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                rules:
                  type: array
                  items:
                    type: object
                    properties:
                      ruleName:
                        type: string
                        enum:
                        - "Exec Whitelisted"
                        - "Unexpected file access"
                        - "Unexpected system call"
                        - "Unexpected capability used"
                        - "Unexpected domain request"
                        - "Exec from malicious source"
                      severity:
                        type: string
                      parameters:
                        type: object
                        additionalProperties: true
                podSelector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            type: array
                            items:
                              type: string
                namespaceSelector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            type: array
  names:
    plural: runtimerulealertbindings
    singular: runtimerulealertbinding
    kind: RuntimeRuleAlertBinding
    shortNames:
      - rab
