apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: runtimerulealertbindings.kubescape.io
spec:
  group: kubescape.io
  names:
    kind: RuntimeRuleAlertBinding
    plural: runtimerulealertbindings
    shortNames:
    - rab
    singular: runtimerulealertbinding
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              namespaceSelector:
                properties:
                  matchExpressions:
                    items:
                      properties:
                        key:
                          type: string
                        operator:
                          type: string
                        values:
                          items:
                            type: string
                          type: array
                      type: object
                    type: array
                  matchLabels:
                    additionalProperties:
                      type: string
                    type: object
                type: object
              podSelector:
                properties:
                  matchExpressions:
                    items:
                      properties:
                        key:
                          type: string
                        operator:
                          type: string
                        values:
                          items:
                            type: string
                          type: array
                      type: object
                    type: array
                  matchLabels:
                    additionalProperties:
                      type: string
                    type: object
                type: object
              rules:
                items:
                  oneOf:
                  - not:
                      anyOf:
                      - required:
                        - ruleID
                      - required:
                        - ruleName
                    required:
                    - ruleTags
                  - not:
                      anyOf:
                      - required:
                        - ruleTags
                      - required:
                        - ruleName
                    required:
                    - ruleID
                  - not:
                      anyOf:
                      - required:
                        - ruleTags
                      - required:
                        - ruleID
                    required:
                    - ruleName
                  properties:
                    parameters:
                      additionalProperties: true
                      type: object
                    ruleID:
                      enum:
                      - R0001
                      - R0002
                      - R0003
                      - R0004
                      - R0005
                      - R1001
                      - R1002
                      - R1003
                      - R1000
                      type: string
                    ruleName:
                      enum:
                      - Exec Whitelisted
                      - Unexpected file access
                      - Unexpected system call
                      - Unexpected capability used
                      - Unexpected domain request
                      - Exec Binary Not In Base Image
                      - Kernel Module Load
                      - Malicious SSH Connection
                      - Exec from malicious source
                      type: string
                    ruleTags:
                      items:
                        enum:
                        - base image
                        - binary
                        - capabilities
                        - connection
                        - dns
                        - exec
                        - kernel
                        - load
                        - malicious
                        - module
                        - open
                        - port
                        - signature
                        - ssh
                        - syscall
                        - whitelisted
                        type: string
                      type: array
    served: false
    storage: false
