FROM golang:1.21.1-alpine3.18 as builder
WORKDIR /go/src/app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o malicious cmd/malicious-exe/malicious.go

FROM alpine:3.18
COPY --from=builder /go/src/app/malicious /malicious
ENTRYPOINT ["/malicious"]
