# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kubecop:
  alertmanager:
    smtp_endpoint: ""
    smtp_from: ""
    smtp_auth_username: ""
    smtp_auth_password: ""
    smtp_require_tls: false
    email_to: ""

