apiVersion: v2
name: kubecop
description: A Helm chart for Kubernetes Runtime Security detection system KubeCop

type: application

version: 0.0.33

appVersion: "0.0.33"


dependencies:
  - name: kubecop-clustered-crds
    version: 0.0.1
    repository: "file://./charts/clustered-crds"
    condition: isClusterScoped
  - name: kubecop-namespaced-crds
    version: 0.0.1
    repository: "file://./charts/namespaced-crds"
    condition: isNamespaced