image:
  repository: kubecop
  tag: latest
  pullPolicy: IfNotPresent
kubecop:
  recording:
    samplingInterval: 60s
    finalizationDuration: 120s
    finalizationJitter: 1s
  alertmanager:
    enabled: true
    endpoints: "alertmanager-operated.monitoring.svc.cluster.local:9093"