{{- $svcName := (printf "armo-admission-webhook.%s.svc" .Release.Namespace) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}-admission
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "..name" . }}-admission
    {{- include "..labels" . | nindent 4 }}
spec:
  replicas: 1  # Set as needed
  selector:
    matchLabels:
      app: {{ include "..name" . }}-admission
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "..name" . }}-admission
        {{- include "..labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "..serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-admission
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --mode-admission-controller
          securityContext:
            {{- toYaml .Values.securityContextNormal | nindent 12 }}
          resources:
            {{- toYaml .Values.kubecop.resources | nindent 12 }}
          env:
            {{- if .Values.isNamespaced }}
            - name: STORE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- end }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/certs
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: {{ $svcName }}-armo-tls-pair
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}