{{- $ca := genCA (printf "*.%s.svc" .Release.Namespace) 1024 -}}
{{- $svcName := (printf "armo-admission-webhook.%s.svc" .Release.Namespace) -}}
{{- $cert := genSignedCert $svcName nil (list $svcName) 1024 $ca -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $svcName }}-armo-tls-pair
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.key: {{ $cert.Key | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation
webhooks:
  - name: validation.armo.admission
    clientConfig:
      service:
        name: armo-admission-webhook
        namespace: {{ .Release.Namespace }}
        path: /validate
        port: 443
      caBundle: {{ $ca.Cert | b64enc }}
    admissionReviewVersions: ["v1"]
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE", "CONNECT"]
        apiGroups: ["*"]
        apiVersions: ["v1"]
        resources: ["pods", "pods/exec"]
        scope: "*"
    failurePolicy: Ignore

