apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "..fullname" . }}
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods", "serviceaccounts"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["apps","batch","extensions"]
  resources: ["*"]
  verbs: ["get"]
- apiGroups: ["kubescape.io"]
  resources: ["applicationprofiles", "namespaces/*/*", "namespaces/*/applicationprofiles/*"]
  verbs: ["watch", "create", "update", "get"]
- apiGroups: ["kubescape.io"]
  resources: ["runtimerulealertbindings"]
  verbs: ["list", "watch"]
