kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "..serviceAccountName" . }}-binding
subjects:
- kind: ServiceAccount
  name: {{ include "..serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "..fullname" . }}
  apiGroup: rbac.authorization.k8s.io