name: Release Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io/armosec
        username: ${{ secrets.QUAYIO_REGISTRY_USERNAME }}
        password: ${{ secrets.QUAYIO_REGISTRY_PASSWORD }}

    - name: Extract tag name
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Containerfile
        push: true
        tags: quay.io/armosec/kubecop:${{ env.TAG_NAME }}

  create-release:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: true
        body: "Autogenerated release for ${{ github.ref }}"
